name: Publish NPM packages

on:
  workflow_dispatch:
    inputs:
      version: 
        description: "Package version number"  
      wix-velo/external-db-airtable:
        type: boolean
        description: "@wix-velo/external-db-airtable"
        default: true

      wix-velo/external-db-bigquery:
        type: boolean
        description: "@wix-velo/external-db-bigquery"
        default: true

jobs:
  publish_npm_ackage:
  
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Installing NX
        run: npm install -g nx

      - run: npm install 

      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/workflows/script.js')
            await script({github, context, core})
            


